-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Administrator CASCADE;
DROP TABLE IF EXISTS FlightInformation CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS ProductType CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;